8 missing sweetest for external id
holochain-open-dev/holoom pull request #62
Opened 2024-08-01 13:11 UTC by nphias

2024-08-01 14:01 UTC, 8e8b2c requested changes
Nice, just a few changes please.

2024-08-01 14:01 UTC, 8e8b2c commented on crates/holoom_dna_tests/src/tests/username_registry/external_id_attestation.rs
> +//this test anticipates future code changes that chnage tht behaviour
Spelling! I know I've asked you delete this test anyway, but this seems like a good opportunity to remind you about:
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2024-08-01 16:30 UTC, nphias commented
done

2024-08-02 08:51 UTC, 8e8b2c approved these changes
Thanks!

2024-08-02 08:59 UTC, merged